---
title: "Dog breeds"
author: "David Hojdan"
date: "5 2 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dplyr)
library(stringr)
library(ggplot2)
library(openxlsx)
library(ggstatsplot)
library(ggdist)

breed_traits <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-02-01/breed_traits.csv')
trait_description <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-02-01/trait_description.csv')
breed_rank_all <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-02-01/breed_rank.csv')

```

```{r wrangling}
breed_traits <- breed_traits %>% 
   mutate(Breed = str_replace_all(string = Breed, 
                                  pattern = "[[:space:]]", 
                                  replacement = " "))
breed_rank_all <- breed_rank_all %>% 
   mutate(Breed = str_replace_all(string = Breed, 
                                  pattern = "[[:space:]]", 
                                  replacement = " "))

breed_traits_data <- breed_traits %>%
  left_join(breed_rank_all, by = "Breed") %>%
  rename("Rank_2013" = "2013 Rank",
         "Rank_2014" = "2014 Rank",
         "Rank_2015" = "2015 Rank",
         "Rank_2016" = "2016 Rank",
         "Rank_2017" = "2017 Rank",
         "Rank_2018" = "2018 Rank",
         "Rank_2019" = "2019 Rank",
         "Rank_2020" = "2020 Rank") %>%
  mutate(Rank_avg = (Rank_2013 + Rank_2014 + Rank_2015 + Rank_2016 + Rank_2017 + Rank_2018 + Rank_2019 + Rank_2020)/8)

names(breed_traits_data) <- gsub(" ", "_", names(breed_traits_data))
```

```{r fig_1 Playfulness}
violin_playfulness <- breed_traits_data %>%
  filter(Playfulness_Level > 2)

playfulness_plot <- ggplot(violin_playfulness, aes(x = Playfulness_Level, y = Rank_avg, color = as.factor(Playfulness_Level))) +
  scale_fill_manual(values=c("#fa8775", "#ea5f94", "#cd34b5")) +
  scale_color_manual(values=c("#fa8775", "#ea5f94", "#cd34b5")) +
  stat_halfeye(adjust = .4, aes(fill = as.factor(Playfulness_Level), alpha = 0.2), point_size = 3, .width = 1) +
  theme_minimal() + 
  theme(panel.background = element_rect(fill = '#2A2A2E', colour = '#2A2A2E'),
        plot.background = element_rect(fill = "#2A2A2E"),
        plot.title = element_text(size = 16, color = "#D2D2D2", hjust = 0,  face = "bold"),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_line(size = 0.2, colour = "#A4A4A4"),
        panel.grid.major.y = element_line(size = 0.2, colour = "#A4A4A4"),
        axis.text.x = element_text(color = "#D2D2D2"),
        axis.title.x = element_text(color = "#D2D2D2", size = 10, hjust = 1),
        axis.text.y = element_text(color = "#D2D2D2"),
        axis.title.y = element_text(color = "#D2D2D2", size = 10, hjust = 1),
        legend.position = "none") +
  labs(title = "Popularity comes with playfulness ") +
  xlab("Level of playfulness") +
  ylab("Popularity ranking (1 - most popular)") +
  scale_x_continuous(breaks = seq(3, 5, 1)) +
  scale_y_reverse(breaks = c(1, 50, 100, 150, 200))

print(playfulness_plot)
  
ggsave(dpi = "retina", plot = playfulness_plot, "playfulness.png", type = "cairo-png", width = 6, height = 5)
```

```{r fig_2 Barking}
violin_barking <- breed_traits_data %>%
  filter(Barking_Level >= 1)

barking_plot <- ggplot(violin_barking, aes(x = Barking_Level, y = Rank_avg, color = as.factor(Barking_Level))) +
  scale_fill_manual(values=c("#fa8775", "#ea5f94", "#cd34b5", "#9d02d7", "#0000ff")) +
  scale_color_manual(values=c("#fa8775", "#ea5f94", "#cd34b5", "#9d02d7", "#0000ff")) +
  stat_halfeye(adjust = .4, aes(fill = as.factor(Barking_Level), alpha = 0.2), point_size = 3, .width = 1) +
  theme_minimal() + 
  theme(panel.background = element_rect(fill = '#2A2A2E', colour = '#2A2A2E'),
        plot.background = element_rect(fill = "#2A2A2E"),
        plot.title = element_text(size = 16, color = "#D2D2D2", hjust = 0,  face = "bold"),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_line(size = 0.2, colour = "#A4A4A4"),
        panel.grid.major.y = element_line(size = 0.2, colour = "#A4A4A4"),
        axis.text.x = element_text(color = "#D2D2D2"),
        axis.title.x = element_text(color = "#D2D2D2", size = 10, hjust = 1),
        axis.text.y = element_text(color = "#D2D2D2"),
        axis.title.y = element_text(color = "#D2D2D2", size = 10, hjust = 1),
        legend.position = "none") +
  labs(title = "Woof, woof") +
  xlab("Level of Barking") +
  ylab("Popularity ranking (1 - most popular)") +
  scale_x_continuous(breaks = seq(1, 5, 1)) +
  scale_y_reverse(breaks = c(1, 50, 100, 150, 200))
  
print(barking_plot)

ggsave(dpi = "retina", plot = barking_plot, "barking.png", type = "cairo-png", width = 6, height = 5)
```








